; Auto-generated. Do not edit!


(cl:in-package fetchit_challenge-msg)


;//! \htmlinclude SchunkMachineGoal.msg.html

(cl:defclass <SchunkMachineGoal> (roslisp-msg-protocol:ros-message)
  ((state
    :reader state
    :initarg :state
    :type cl:integer
    :initform 0))
)

(cl:defclass SchunkMachineGoal (<SchunkMachineGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SchunkMachineGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SchunkMachineGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fetchit_challenge-msg:<SchunkMachineGoal> is deprecated: use fetchit_challenge-msg:SchunkMachineGoal instead.")))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <SchunkMachineGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fetchit_challenge-msg:state-val is deprecated.  Use fetchit_challenge-msg:state instead.")
  (state m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<SchunkMachineGoal>)))
    "Constants for message type '<SchunkMachineGoal>"
  '((:OPEN . 0)
    (:CLOSE . 1)
    (:START_OPERATION . 2)
    (:END_OPERATION . 3))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'SchunkMachineGoal)))
    "Constants for message type 'SchunkMachineGoal"
  '((:OPEN . 0)
    (:CLOSE . 1)
    (:START_OPERATION . 2)
    (:END_OPERATION . 3))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SchunkMachineGoal>) ostream)
  "Serializes a message object of type '<SchunkMachineGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'state)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'state)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'state)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'state)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SchunkMachineGoal>) istream)
  "Deserializes a message object of type '<SchunkMachineGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'state)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SchunkMachineGoal>)))
  "Returns string type for a message object of type '<SchunkMachineGoal>"
  "fetchit_challenge/SchunkMachineGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SchunkMachineGoal)))
  "Returns string type for a message object of type 'SchunkMachineGoal"
  "fetchit_challenge/SchunkMachineGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SchunkMachineGoal>)))
  "Returns md5sum for a message object of type '<SchunkMachineGoal>"
  "9074e47af1bcfb0750a3fc3714bddb62")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SchunkMachineGoal)))
  "Returns md5sum for a message object of type 'SchunkMachineGoal"
  "9074e47af1bcfb0750a3fc3714bddb62")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SchunkMachineGoal>)))
  "Returns full string definition for message of type '<SchunkMachineGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 OPEN=0~%uint32 CLOSE=1~%uint32 START_OPERATION=2~%uint32 END_OPERATION=3~%uint32 state ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SchunkMachineGoal)))
  "Returns full string definition for message of type 'SchunkMachineGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 OPEN=0~%uint32 CLOSE=1~%uint32 START_OPERATION=2~%uint32 END_OPERATION=3~%uint32 state ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SchunkMachineGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SchunkMachineGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SchunkMachineGoal
    (cl:cons ':state (state msg))
))
