; Auto-generated. Do not edit!


(cl:in-package fetchit_challenge-msg)


;//! \htmlinclude SchunkMachineFeedback.msg.html

(cl:defclass <SchunkMachineFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SchunkMachineFeedback (<SchunkMachineFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SchunkMachineFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SchunkMachineFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fetchit_challenge-msg:<SchunkMachineFeedback> is deprecated: use fetchit_challenge-msg:SchunkMachineFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SchunkMachineFeedback>) ostream)
  "Serializes a message object of type '<SchunkMachineFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SchunkMachineFeedback>) istream)
  "Deserializes a message object of type '<SchunkMachineFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SchunkMachineFeedback>)))
  "Returns string type for a message object of type '<SchunkMachineFeedback>"
  "fetchit_challenge/SchunkMachineFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SchunkMachineFeedback)))
  "Returns string type for a message object of type 'SchunkMachineFeedback"
  "fetchit_challenge/SchunkMachineFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SchunkMachineFeedback>)))
  "Returns md5sum for a message object of type '<SchunkMachineFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SchunkMachineFeedback)))
  "Returns md5sum for a message object of type 'SchunkMachineFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SchunkMachineFeedback>)))
  "Returns full string definition for message of type '<SchunkMachineFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SchunkMachineFeedback)))
  "Returns full string definition for message of type 'SchunkMachineFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SchunkMachineFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SchunkMachineFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SchunkMachineFeedback
))
