; Auto-generated. Do not edit!


(cl:in-package fetchit_challenge-msg)


;//! \htmlinclude SickCameraFeedback.msg.html

(cl:defclass <SickCameraFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SickCameraFeedback (<SickCameraFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SickCameraFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SickCameraFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fetchit_challenge-msg:<SickCameraFeedback> is deprecated: use fetchit_challenge-msg:SickCameraFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SickCameraFeedback>) ostream)
  "Serializes a message object of type '<SickCameraFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SickCameraFeedback>) istream)
  "Deserializes a message object of type '<SickCameraFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SickCameraFeedback>)))
  "Returns string type for a message object of type '<SickCameraFeedback>"
  "fetchit_challenge/SickCameraFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SickCameraFeedback)))
  "Returns string type for a message object of type 'SickCameraFeedback"
  "fetchit_challenge/SickCameraFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SickCameraFeedback>)))
  "Returns md5sum for a message object of type '<SickCameraFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SickCameraFeedback)))
  "Returns md5sum for a message object of type 'SickCameraFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SickCameraFeedback>)))
  "Returns full string definition for message of type '<SickCameraFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SickCameraFeedback)))
  "Returns full string definition for message of type 'SickCameraFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SickCameraFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SickCameraFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SickCameraFeedback
))
