; Auto-generated. Do not edit!


(cl:in-package fetchit_challenge-msg)


;//! \htmlinclude SickCameraGoal.msg.html

(cl:defclass <SickCameraGoal> (roslisp-msg-protocol:ros-message)
  ((trigger
    :reader trigger
    :initarg :trigger
    :type cl:integer
    :initform 0))
)

(cl:defclass SickCameraGoal (<SickCameraGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SickCameraGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SickCameraGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fetchit_challenge-msg:<SickCameraGoal> is deprecated: use fetchit_challenge-msg:SickCameraGoal instead.")))

(cl:ensure-generic-function 'trigger-val :lambda-list '(m))
(cl:defmethod trigger-val ((m <SickCameraGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fetchit_challenge-msg:trigger-val is deprecated.  Use fetchit_challenge-msg:trigger instead.")
  (trigger m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<SickCameraGoal>)))
    "Constants for message type '<SickCameraGoal>"
  '((:TRIG . 0))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'SickCameraGoal)))
    "Constants for message type 'SickCameraGoal"
  '((:TRIG . 0))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SickCameraGoal>) ostream)
  "Serializes a message object of type '<SickCameraGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'trigger)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'trigger)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'trigger)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'trigger)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SickCameraGoal>) istream)
  "Deserializes a message object of type '<SickCameraGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'trigger)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'trigger)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'trigger)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'trigger)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SickCameraGoal>)))
  "Returns string type for a message object of type '<SickCameraGoal>"
  "fetchit_challenge/SickCameraGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SickCameraGoal)))
  "Returns string type for a message object of type 'SickCameraGoal"
  "fetchit_challenge/SickCameraGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SickCameraGoal>)))
  "Returns md5sum for a message object of type '<SickCameraGoal>"
  "a00eab466ee4a5a785a998c5366a7e21")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SickCameraGoal)))
  "Returns md5sum for a message object of type 'SickCameraGoal"
  "a00eab466ee4a5a785a998c5366a7e21")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SickCameraGoal>)))
  "Returns full string definition for message of type '<SickCameraGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 TRIG=0~%uint32 trigger~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SickCameraGoal)))
  "Returns full string definition for message of type 'SickCameraGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 TRIG=0~%uint32 trigger~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SickCameraGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SickCameraGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SickCameraGoal
    (cl:cons ':trigger (trigger msg))
))
